name: GoCars
main: com.owen2k6.gocars.GoCars
version: 0.3.1a
author: Owen2k6
commands:
  car:
    description: Turns your boat into a car
    usage: /<command>
  boat:
    description: Turns your car into a boat
    usage: /<command>
  dvla:
    description: Shows the DVLA commands
    usage: /<command>
permissions:
    dvla.scan:
        description: Allows you to see full information of any users licence.
        default: op